---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: test

  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v4

  #  - name: Set up Python
  #    uses: actions/setup-python@v2
  #    with:
  #      python-version: '3.12'

  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install -r requirements.txt

  #  - name: Deploy to AWS
  #    run: |
  #      aws s3 sync . s3://my-bucket-name
